# Generated by Django 3.2 on 2021-04-29 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='createdAt',
            field=models.DateField(auto_now_add=True, default=datetime.date.today, verbose_name='Criate at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='updateAt',
            field=models.DateField(auto_now=True, verbose_name='Update at'),
        ),
    ]
