# Generated by Django 3.2 on 2021-04-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210429_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='createdAt',
            field=models.DateField(auto_now_add=True, verbose_name='Create at'),
        ),
    ]
